# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    concat:
      repo: puppetlabs/concat
      ref: 6.4.0
    gitlab:
      repo: puppet/gitlab
      ref: 8.0.0
    postgresql:
      repo: puppetlabs/postgresql
      ref: 6.10.1
    puppet:
      repo: aursu/puppet
      ref: 0.1.5
    selinux:
      repo: puppet/selinux
      ref: 3.2.0
    stdlib:
      repo: puppetlabs/stdlib
      ref: 6.6.0
    tlsinfo:
      repo: aursu/tlsinfo
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
    cron_core:
      repo: puppetlabs/cron_core
      puppet_version: ">= 6.0.0"
  repositories:
    dockerinstall:
      repo: https://github.com/aursu/puppet-dockerinstall.git
      ref: tags/v0.9.5
    lsys:
      repo: https://github.com/aursu/puppet-lsys.git
      ref: tags/v0.18.0
    nginx:
      repo: https://github.com/aursu/puppet-nginx.git
      ref: tags/v3.0.1-rc0.1
